# Generated by Django 6.0.6 on 2026-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, default='#4F46E5', help_text='Hex color for the icon badge', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, default='fa-screwdriver-wrench', help_text='Font Awesome class e.g. fa-bolt', max_length=50),
        ),
    ]
